### ISSUE TITLE
Add Zettlr

### ISSUE THREAD

**Issue by lrq3000** [ashwinvis/awesome-scientific-writing#11]
Hello,

I would just like to suggest to add [Zettlr](https://www.zettlr.com/), a great opensource alternative to Evernote, which supports bibliography, footnotes and import/export to and from LaTeX (and other formats like Word DOC, etc).

**Comment by ashwinvis** [comment]
Is #12 a satisfactory description?

**Comment by lrq3000** [comment]
@ashwinvis Yes awesome! I would just add that it is WYSIWYG, which is quite rare for Markdown editors. Thank you very much!
